### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [docteurem/HersheyReturns#2]
hi , sorry to open ticket for my question , do you know instruction or software to convert specific fonts (Persian ) to Hershey fonts?

**Comment by docteurem** [comment]
Hi, to my knowledge there is no software to convert specific font to Hershey format: I understand it could be interesting to automatically convert a font to vector (for this you'll need to find the skeletons for each glyph) but I don't really see why you would want to convert it to Hershey (?)

**Comment by mkeyno** [comment]
actually I use GRBL-plotter for my diy cnc cutter , this software is open source and easily can convert a text to G-code , however I found that to support new font , hershey font should be installed , but according to some comment that I've received yet it is not easy as it should be
