### ISSUE TITLE
Bottom of rounded letters getting cut off in "futuram" and "futural"

### ISSUE THREAD

**Issue by hamamoto** [docteurem/HersheyReturns#3]
it seems like the bottom of rounded bottom characters (o, e), when there are no descenders is getting cut off.

similarly, the bottom of rounded bottom descenders (g), sees the same thing happening.

<img width="360" alt="screen shot 2018-06-04 at 10 37 31 pm" src="https://user-images.githubusercontent.com/3487788/40953982-020e9d30-6848-11e8-8cfe-e5b2dad70a8d.png">

**Comment by docteurem** [comment]
Hello, this project has moved to https://gitlab.com/lionelmaes/HersheyReturns. I will check on your issue today and update the repo!
